### ISSUE TITLE
Open The Right of the Viewport

### ISSUE THREAD

**Issue by TiddlyTweeter** [reidgould/tiddlywiki-dropboard#1]
I think this is a great piece of work. Very rich.

I know right now you looking at debugging extant code, not new innovations.

BUT let me say one thing: "**Open The Right**". The horizontal extension of the board beyond the confines of current TW borders would give users stronger reasons to use it and, combined with the brilliant "collapse to narrow column" mechanism you already built, could enable many types of app.

Best wishes
Josiah

**Comment by reidgould** [comment]
Try adding several more tiddlers as lists in a board and see the way the horizontal scrollbar appears to allow you to scroll to see the additional lists to the right.

Is this the kind of extension you mean by "open the right"?

**Comment by TiddlyTweeter** [comment]
Ciao Reid

Its okay but its still too crampt I think. What I mean is more radical. Somewhat like Riz did taking over the forefront. Visually I think that is correct for this kind of app. 

But I can see it may be possible in a single Tiddler in normal stream but only if you reduce to the minimum around it all padding & margins to  have access to maximal HORIZONTAL SPACE. As is its a tension.

Best wishes
Josiah

**Comment by reidgould** [comment]
What do you think about the "Window" button? Are there any reasons that the separate window does not suit your use case or visual preferences?

**Comment by reidgould** [comment]
The method Riz is using to take over the wiki's main interface has one significant disadvantage. He is removing the tag from the main UI elements that causes them to be displayed, but because they are shadow tiddlers they cannot be modified directly. What actually happens is a copy of each of the UI elements is created in your wiki with the only difference being without the tag. If future versions of TW change any of these tiddlers, you will have to manually go and delete the copies so that the new versions will be used. This problem can even follow you to other wikis that have never had the plugin installed if you export the contents and import them without remembering to exclude the UI tiddlers. In my opinion, its too big and too hidden of an issue to ship to unaware users.

**Comment by TiddlyTweeter** [comment]
Ciao Reid

_I slept on it_ and why it matters to me 'cause I realised I was being a bit over-pushy. Explaining a **Use Case** I'm interested in may clarify the specific issues better... 

- Making an **online**  resource to list tweets, somewhat like Tweetdeck. 

- What the user would see would ONLY be the columns and and column headers. The menu items would be hidden and much of the rest of the TW interface too. 

- Oriented to USE of the content, not sophisticated rearrangement (that being mainly for me in the off-line version setting it up.)

What I realised was that, _of course,_ that's largely a CSS issue that *I* would be dealing with, not necessarily, you, the creator of the base mechanism.

Coming to your question ...

> What do you think about the "Window" button? Are there any reasons that the separate window does not suit your use case or visual preferences? 

For local use, since I use a PC with extra monitors its fine.

I will look at the CSS to check it will enable me to easily do what I'd like and post a request for changes if it doesn't

I think you can close this issue.

Best wishes for your really fine, useful, tool!

Josiah

**Comment by reidgould** [comment]
That is an interesting possibility. Perhaps a "read only" mode to disable user listops could be a part of a future version.

Thanks Josiah, I hope you find success integrating Dropboard into your wikis.

Reid
