### ISSUE TITLE
wikilink not open

### ISSUE THREAD

**Issue by nasredin** [reidgould/tiddlywiki-dropboard#5]
Hello,

i just trying your project... it is very good... but if i use wikilink [[xyz]] and click it it doesn't do anything.
i tried it also on your examplke webpage, u have link "client" there and it also doesnt work... tested in chrome and safari...

could u help? is project still alive?

thx

**Comment by reidgould** [comment]
Hi @nasredin, thanks for reporting. This is a known issue. A proper fix would be non-trivial, but if you want to work on it and submit a pull request I would consider accepting a fix. 

Dropboard's lists are implemented using [Navigator](https://tiddlywiki.com/#NavigatorWidget) widgets, just like the main story. Unfortunately due to the special features of Dropboard normal link opening doesn't work right, so I disabled it using a [Linkcatcher](https://tiddlywiki.com/#LinkCatcherWidget) which you can see in the [List.tid](https://github.com/reidgould/tiddlywiki-dropboard/blob/gh-default/Source/editions/dropboard-plugin/plugins/dropboard/tiddlers/templates/view/List.tid) file. Workarounds are to drag the link to the location you want it to appear in a list, or to drag it to "Open In Main Story" drop area in the toolbar to open it outside of the board.

If you spot any other issues, let me know!

**Comment by nasredin** [comment]
thanks for reply, i'm happy for info... i will check it when i will have some time :)

btw your plugin is awesome!
